package com.sift.gl.model;
// Generated Nov 11, 2010 5:32:25 PM by Hibernate Tools 3.2.1.GA

import com.sift.gl.model.Accountsegmentdetails;
import java.util.List;

/**
 * Accountsegments generated by hbm2java
 */
public class Accountsegmentdetlist  {
    private List<Accountsegmentdetails> accsegdets;
    
    public Accountsegmentdetlist() {
        
    }
    public Accountsegmentdetlist(List<Accountsegmentdetails> accsegdets) {
        this.accsegdets = accsegdets;
    }
    public List<Accountsegmentdetails> getAccsegdets() {
        return accsegdets;
    }
 
    public void setAccsegdets(List<Accountsegmentdetails> accsegdets) {
        this.accsegdets = accsegdets;
    }
}


