package com.sift.gl.model;
// Generated Nov 11, 2010 5:32:25 PM by Hibernate Tools 3.2.1.GA



/**
 * Accountstructures generated by hbm2java
 */
public class Accountstructuresdetails  implements java.io.Serializable {


     private Integer acStrId;
     //private String structureCode;
     private String structurecode;
     private Integer sequenceNo;
     private Integer segmentId;
     private Integer seg1;
     private Integer seg2=0;
     private Integer seg3=0;
     private Integer seg4=0;
     private Integer seg5=0;
     private Integer seg6=0;
     private Integer seg7=0;
     private Integer seg8=0;
     private Integer seg9=0;
     private Integer seg10=0;
     private String segdesc1="";
     private String segdesc2="";
     private String segdesc3="";
     private String segdesc4="";
     private String segdesc5="";
     private String segdesc6="";
     private String segdesc7="";
     private String segdesc8="";
     private String segdesc9="";
     private String segdesc10="";
     private Integer segmentLength;
     private String delimiter;
     private String segmentName;
     private String description;
     private Integer company;
     
    public Accountstructuresdetails() {
    }

	
    public Accountstructuresdetails(String structurecode) {
        this.structurecode = structurecode;
    }
    public Accountstructuresdetails(String structurecode, Integer sequenceNo, Integer segmentId, Integer segmentLength, String delimiter,Integer company) {
       this.structurecode = structurecode;
       this.sequenceNo = sequenceNo;
       this.segmentId = segmentId;
       this.segmentLength = segmentLength;
       this.delimiter = delimiter;
       this.company = company;
    }
   
    public Integer getAcStrId() {
        return this.acStrId;
    }
    
    public void setAcStrId(Integer acStrId) {
        this.acStrId = acStrId;
    }
    public String getStructurecode() {
        return this.structurecode;
    }
    
    public void setStructurecode(String structurecode) {
        this.structurecode = structurecode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
    public Integer getSegmentId() {
        return this.segmentId;
    }
    
    public void setSegmentId(Integer segmentId) {
        this.segmentId = segmentId;
    }
    public Integer getSeg1() {
        return this.seg1;
    }
    public void setSeg1(Integer seg1) {
        this.seg1 = seg1;
    }
    public Integer getSeg2() {
        return this.seg2;
    }
    public void setSeg2(Integer seg2) {
        this.seg2 = seg2;
    }
    public Integer getSeg3() {
        return this.seg3;
    }
    public void setSeg3(Integer seg3) {
        this.seg3 = seg3;
    }
    public Integer getSeg4() {
        return this.seg4;
    }
    public void setSeg4(Integer seg4) {
        this.seg4 = seg4;
    }
    public Integer getSeg5() {
        return this.seg5;
    }
    public void setSeg5(Integer seg5) {
        this.seg5 = seg5;
    }
    public Integer getSeg6() {
        return this.seg6;
    }
    public void setSeg6(Integer seg6) {
        this.seg6 = seg6;
    }
    public Integer getSeg7() {
        return this.seg7;
    }
    public void setSeg7(Integer seg7) {
        this.seg7 = seg7;
    }
    public Integer getSeg8() {
        return this.seg8;
    }
    public void setSeg8(Integer seg8) {
        this.seg8 = seg8;
    }
    public Integer getSeg9() {
        return this.seg9;
    }
    public void setSeg9(Integer seg9) {
        this.seg9 = seg9;
    }
    public Integer getSeg10() {
        return this.seg10;
    }
    public void setSeg10(Integer seg10) {
        this.seg10 = seg10;
    }
    public String getSegdesc1() {
        return this.segdesc1;
    }
    public void setSegdesc1(String segdesc1) {
        this.segdesc1 = segdesc1;
    }
    public String getSegdesc2() {
        return this.segdesc2;
    }
    public void setSegdesc2(String segdesc2) {
        this.segdesc2 = segdesc2;
    }
    public String getSegdesc3() {
        return this.segdesc3;
    }
    public void setSegdesc3(String segdesc3) {
        this.segdesc3 = segdesc3;
    }
    public String getSegdesc4() {
        return this.segdesc4;
    }
    public void setSegdesc4(String segdesc4) {
        this.segdesc4 = segdesc4;
    }
    public String getSegdesc5() {
        return this.segdesc5;
    }
    public void setSegdesc5(String segdesc5) {
        this.segdesc5 = segdesc5;
    }
    public String getSegdesc6() {
        return this.segdesc6;
    }
    public void setSegdesc6(String segdesc6) {
        this.segdesc6 = segdesc6;
    }
    public String getSegdesc7() {
        return this.segdesc7;
    }
    public void setSegdesc7(String segdesc7) {
        this.segdesc7 = segdesc7;
    }
    public String getSegdesc8() {
        return this.segdesc8;
    }
    public void setSegdesc8(String segdesc8) {
        this.segdesc8 = segdesc8;
    }
    public String getSegdesc9() {
        return this.segdesc9;
    }
    public void setSegdesc9(String segdesc9) {
        this.segdesc9 = segdesc9;
    }
    public String getSegdesc10() {
        return this.segdesc10;
    }
    public void setSegdesc10(String segdesc10) {
        this.segdesc10 = segdesc10;
    }
    
    public Integer getSegmentLength() {
        return this.segmentLength;
    }
    
    public void setSegmentLength(Integer segmentLength) {
        this.segmentLength = segmentLength;
    }
    public String getDelimiter() {
        return this.delimiter;
    }
    
    public void setDelimiter(String delimiter) {
        this.delimiter = delimiter;
    }

    public String getsegmentName() {
        return this.segmentName;
    }

    public void setsegmentName(String segmentName) {
        this.segmentName = segmentName;
    }
     public Integer getCompany() {
        return this.company;
    }
    
    public void setCompany(Integer company) {
        this.company = company;
    }


}


