package com.sift.gl.model;
// Generated Nov 11, 2010 5:32:25 PM by Hibernate Tools 3.2.1.GA

/**
 * Users generated by hbm2java
 */
public class Holidatesdet {

     private Integer recurring;
     private String holidate;
     private Integer branch;
     private Integer companyid;
     private String description;
     private Integer id;

    public Holidatesdet() {
    }

    public Holidatesdet(Integer recurring, String holidate, Integer branch, String description, Integer companyid) {
       this.recurring = recurring;
       this.holidate = holidate;
       this.branch = branch;
       this.description = description;
       this.companyid = companyid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getHolidate() {
        return this.holidate;
    }
    
    public void setHolidate(String holidate) {
        this.holidate = holidate;
    }
    public Integer getRecurring() {
        return this.recurring;
    }
    public void setRecurring(Integer recurring) {
        this.recurring = recurring;
    }
    public Integer getBranch() {
        return this.branch;
    }
    
    public void setBranch(Integer branch) {
        this.branch = branch;
    }
    public String getDescription() {
        return this.description;
    }
    public Integer getCompanyid() {
        return this.companyid;
    }
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    
}


