package com.sift.gl.model;
// Generated Dec 10, 2010 1:01:16 PM by Hibernate Tools 3.2.1.GA



/**
 * Modules generated by hbm2java
 */
public class Moduledetails  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String description;
     private String icon;
     private Integer sortorder;
     private String modulerole;
     boolean enabled;
     private String active;

    public Moduledetails() {
    }

	
    public Moduledetails(String code) {
        this.code = code;
    }
    public Moduledetails(String code, String description, String icon, Integer sortorder) {
       this.code = code;
       this.description = description;
       this.icon = icon;
       this.sortorder = sortorder;
       //this.enabled = enabled;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }
    public Integer getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(Integer sortorder) {
        this.sortorder = sortorder;
    }
    public boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public String getModulerole() {
        return this.modulerole;
    }
    
    public void setModulerole(String modulerole) {
        this.modulerole = modulerole;
    }

    /**
     * @return the active
     */
    public String getActive() {
        return active;
    }

    /**
     * @param active the active to set
     */
    public void setActive(String active) {
        this.active = active;
    }
}


