package com.sift.gl.model;
// Generated Dec 10, 2010 1:01:16 PM by Hibernate Tools 3.2.1.GA



/**
 * Modules generated by hbm2java
 */
public class Modulemenudetails  implements java.io.Serializable {


     private Integer id;
     private String menucode;
     private String module;
     private String menupath;
     private String displaytext;
     private Integer menusortorder;
     private String menurole;
     boolean enabled;

    public Modulemenudetails() {
    }

	
    public Modulemenudetails(String menucode) {
        this.menucode = menucode;
    }
    public Modulemenudetails(String module,String menucode, String menupath, String displaytext, Integer menusortorder,String menurole) {
       this.menucode = menucode;
       this.menupath = menupath;
       this.displaytext = displaytext;
       this.menusortorder = menusortorder;
       this.module = module;
       this.menurole = menurole;
       //this.enabled = enabled;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMenucode() {
        return this.menucode;
    }
    
    public void setMenucode(String menucode) {
        this.menucode = menucode;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    public String getMenupath() {
        return this.menupath;
    }
    
    public void setMenupath(String menupath) {
        this.menupath = menupath;
    }
    public String getDisplaytext() {
        return this.displaytext;
    }
    
    public void setDisplaytext(String displaytext) {
        this.displaytext = displaytext;
    }
    public Integer getMenusortorder() {
        return this.menusortorder;
    }
    
    public void setMenusortorder(Integer menusortorder) {
        this.menusortorder = menusortorder;
    }
    public boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public String getMenurole() {
        return this.menurole;
    }
    
    public void setMenurole(String menurole) {
        this.menurole = menurole;
    }
}


