package com.sift.gl.model;
// Generated Nov 11, 2010 5:32:25 PM by Hibernate Tools 3.2.1.GA

/**
 * Users generated by hbm2java
 */
public class Settingsdet {


     private String setting;
     private String settingval;
     private Integer branch;
     private Integer companyid;
     private String display;
     private Integer id;

    public Settingsdet() {
    }

	
    public Settingsdet(String setting) {
        this.setting = setting;
    }
    public Settingsdet(String setting, String settingval, Integer branch, String display, Integer companyid) {
       this.setting = setting;
       this.settingval = settingval;
       this.branch = branch;
       this.display = display;
       this.companyid = companyid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSetting() {
        return this.setting;
    }
    
    public void setSetting(String setting) {
        this.setting = setting;
    }
    public String getSettingval() {
        return this.settingval;
    }
    
    public void setSettingval(String settingval) {
        this.settingval = settingval;
    }
    public Integer getBranch() {
        return this.branch;
    }
    
    public void setBranch(Integer branch) {
        this.branch = branch;
    }
    public String getDisplay() {
        return this.display;
    }
    public Integer getCompanyid() {
        return this.companyid;
    }
    
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }
    public void setDisplay(String display) {
        this.display = display;
    }
    
}


