package com.sift.gl.model;
// Generated Nov 11, 2010 5:32:25 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Txnsheader generated by hbm2java
 */
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author yomi-pc
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Txnsheader  implements java.io.Serializable {

     @XmlElement(name = "headerId")
     private Integer headerId;
     @XmlElement(name = "txnSerial")
     private String txnSerial;
     @XmlElement(name = "txnType")
     private String txnType;
     @XmlElement(name = "year")
     private Integer year;
     @XmlElement(name = "period")
     private Integer period;
     @XmlElement(name = "txnDate")
     private Date txnDate;
     @XmlElement(name = "postdate")
     private Date postdate;
     @XmlElement(name = "entrydate")
     private Date entrydate;
     @XmlElement(name = "docRef")
     private String docRef;
     @XmlElement(name = "headernarrative")
     private String headernarrative;
     @XmlElement(name = "userId")
     private String userId;
     @XmlElement(name = "branchId")
     private Integer branchId;
     @XmlElement(name = "source")
     private String source;
     @XmlElement(name = "companyid")
     private Integer companyid;
     @XmlElement(name = "timezone")
     private String timezone;

    public Txnsheader() {
    }

    public Txnsheader(String txnSerial, String txnType,Integer year, Integer period, Date txnDate, Date postdate, Date entrydate, String docRef, String headernarrative,String source, String userId, Integer branchId,Integer companyid,String timezone) {
       this.txnSerial = txnSerial;
       this.txnType = txnType;
       this.year = year;
       this.period = period;
       this.txnDate = txnDate;
       this.postdate = postdate;
       this.entrydate = entrydate;
       this.docRef = docRef;
       this.headernarrative = headernarrative;
       this.userId = userId;
       this.branchId = branchId;
       this.source = source;
       this.companyid = companyid;
       this.timezone = timezone;
    }

    public Integer getHeaderId() {
        return this.headerId;
    }

    public void setHeaderId(Integer headerId) {
        this.headerId = headerId;
    }
    public String getTxnSerial() {
        return this.txnSerial;
    }

    public void setTxnSerial(String txnSerial) {
        this.txnSerial = txnSerial;
    }
    public String getTxnType() {
        return this.txnType;
    }

    public void setTxnType(String txnType) {
        this.txnType = txnType;
    }
    public Integer getPeriod() {
        return this.period;
    }

    public void setPeriod(Integer period) {
        this.period = period;
    }
    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }
    public Date getTxnDate() {
        return this.txnDate;
    }

    public void setTxnDate(Date txnDate) {
        this.txnDate = txnDate;
    }
    public Date getPostdate() {
        return this.postdate;
    }

    public void setPostdate(Date postdate) {
        this.postdate = postdate;
    }
    public Date getEntrydate() {
        return this.entrydate;
    }

    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
    public String getDocRef() {
        return this.docRef;
    }

    public void setDocRef(String docRef) {
        this.docRef = docRef;
    }
    public String getHeadernarrative() {
        return this.headernarrative;
    }

    public void setHeadernarrative(String headernarrative) {
        this.headernarrative = headernarrative;
    }
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Integer getBranchId() {
        return this.branchId;
    }

    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }
    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }
    public Integer getCompanyId() {
        return this.companyid;
    }

    public void setCompanyId(Integer companyId) {
        this.companyid = companyId;
    }
     public String getTimezone() {
        return timezone;
    }
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }
}


